"""add switch language

Revision ID: 75c33b6ecfea
Revises: 5d981f5882ad
Create Date: 2024-01-31 10:47:49.553429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c33b6ecfea'
down_revision: Union[str, None] = '5d981f5882ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mode', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mode')
    # ### end Alembic commands ###
